FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /app/src
COPY src/ .
RUN dotnet restore HouseholdTaskPlanner.TelegramBot.Cli/HouseholdTaskPlanner.TelegramBot.Cli.csproj
RUN dotnet publish -c Release HouseholdTaskPlanner.TelegramBot.Cli/HouseholdTaskPlanner.TelegramBot.Cli.csproj -o /app/build

FROM mcr.microsoft.com/dotnet/core/runtime:3.1
WORKDIR /app
COPY --from=build /app/build/ ./
ENTRYPOINT ["dotnet", "HouseholdTaskPlanner.TelegramBot.Cli.dll"]