version: "3.7"
services:
  task-web:
    image: household-task-web
    build:
      context: .
      dockerfile: src/TaskPlanner/TaskPlanner.Web/Dockerfile
    environment:
      - "ConnectionString=Server=db,1433;Database=HouseholdTaskPlanner;User Id=sa;Password=!1Start1!;"
      - "UserApi__BackendLocation=http://user-web/api"
      - "UserApi__BasicAuth=user:pass"
    restart: unless-stopped

  task-bot:
    image: household-task-bot
    build:
      context: .
      dockerfile: src/TaskPlanner/TaskPlanner.TelegramBot.Cli/Dockerfile
    environment:
      - "BotToken="
      - "ScheduleChat=-123456789"
      - "AllowedChats__0=-123456789"
      - "TaskApi__BackendLocation=http://task-web/api"
      - "TaskApi__BasicAuth=user:pass"
      - "UserApi__BackendLocation=http://user-web/api"
      - "UserApi__BasicAuth=user:pass"
    restart: unless-stopped

  user-web:
    image: household-user-web
    build:
      context: .
      dockerfile: src/User/User.Web/Dockerfile
    environment:
      - "ConnectionString=Server=db,1433;Database=HouseholdTaskPlanner;User Id=sa;Password=!1Start1!;"
    restart: unless-stopped

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "127.0.0.1:14330:1433"
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=!1Start1!"
    volumes: 
      - "db:/var/opt/mssql"
    restart: unless-stopped

volumes:
  db:
