version: "3.7"
services:
  web:
    image: household-planner-web
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      - "ConnectionString=Server=db,1433;Database=BeatSaverMatcher;User Id=sa;Password=!1Start1!;"
    restart: unless-stopped

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "127.0.0.1:14330:1433"
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=!1Start1!"
    volumes: 
      - "db:/var/opt/mssql"
    restart: unless-stopped

volumes:
  db:
